apiVersion: apps/v1
kind: Deployment
metadata:
  name: ims-frontend
  namespace: ims
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ims-frontend
  template:
    metadata:
      labels:
        app: ims-frontend
    spec:
      containers:
        - name: ims-frontend
          image: ahmedwalid1410/ims-frontend-k8s:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "256Mi"
