apiVersion: v1
kind: Service
metadata:
  name: ims-frontend-service
  namespace: ims
spec:
  selector:
    app: ims-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
