apiVersion: v1
kind: Secret
metadata:
  name: ims-backend-secret
  namespace: ims
type: Opaque
stringData:
  MONGODB_URI: "mongodb+srv://ahmedwalid:Ahmed12345@cluster0.vovod7g.mongodb.net/?appName=Cluster0"
  SECRET_KEY: "replace-with-a-long-random-secret"
