apiVersion: v1
kind: Service
metadata:
  name: ims-backend-service
  namespace: ims
spec:
  selector:
    app: ims-backend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
