apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service
  namespace: inventory-management
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
        - name: order-service
          image: ahmedwalid1410/ims-order-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 4003
          env:
            - name: ORDER_SERVICE_PORT
              value: "4003"
            - name: ORDER_MONGO_URI
              value: "mongodb://mongo:27017/inventory_orders"
            - name: INVENTORY_SERVICE_URL
              value: "http://inventory-service:4004"
---
apiVersion: v1
kind: Service
metadata:
  name: order-service
  namespace: inventory-management
spec:
  selector:
    app: order-service
  ports:
    - port: 4003
      targetPort: 4003
  type: ClusterIP
